// <auto-generated />
using System;
using Hovedopgave.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hovedopgave.Migrations
{
    [DbContext(typeof(HovedopgaveContext))]
    partial class HovedopgaveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hovedopgave.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Station");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationX = 1.0,
                            LocationY = 2.0,
                            Name = "Station 1",
                            Notes = "This is station 1"
                        },
                        new
                        {
                            Id = 2,
                            LocationX = 3.0,
                            LocationY = 4.0,
                            Name = "Station 2",
                            Notes = "This is station 2"
                        });
                });

            modelBuilder.Entity("Hovedopgave.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 12, 2, 11, 20, 29, 983, DateTimeKind.Local).AddTicks(5855),
                            Description = "Ticket 1",
                            IsFinished = false,
                            LastUpdated = new DateTime(2024, 12, 2, 11, 20, 29, 983, DateTimeKind.Local).AddTicks(5904),
                            Priority = 1
                        });
                });

            modelBuilder.Entity("Hovedopgave.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "password123",
                            Role = "User",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 3,
                            Password = "password123",
                            Role = "Felt",
                            Username = "felt1"
                        },
                        new
                        {
                            Id = 4,
                            Password = "password123",
                            Role = "Kontor",
                            Username = "kontor1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
